### ISSUE TITLE
Use \leavevmode for divs and \textcolor for spans?

### ISSUE THREAD

**Issue by gandalfsaxe** [chdemko/pandoc-latex-color#1]
Using your own example input:
```markdown
---
pandoc-latex-color:
  - classes: [important]
    color: red
---

::: important ::::::
This is important content
::::::::::::::::::::

This is normal content, [warning content]{latex-color=orange} and [important content]{.important}.
```
will convert fine into PDF via `pandoc -F pandoc-latex-color test.md -o test.pdf`:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/12127864/42039795-81b2a992-7aee-11e8-9912-52e2285c201e.png">

## Problem

However converting it into .tex via `pandoc -F pandoc-latex-color test.md -o test.tex` results in:
```latex
{\color{red} 

This is important content

}

This is normal content, {\color{orange} warning content} and
{\color{red} important content}.
```

This is not so good. If converted into PDF in any way (pandoc, pdflatex etc.), it will give this output:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12127864/42040163-4c244294-7aef-11e8-96ab-4420224a7d2a.png">

## Solution

1. For div (multiple paragraphs), add `\leavevmode` i front (see [this](https://tex.stackexchange.com/questions/207225/writing-paragraphs-in-textcolor) and [this](https://tex.stackexchange.com/questions/49910/how-to-colour-multiple-paragraphs))
2. for span (single paragraph), use `\textcolor` instead of `color`

I.e. the above .tex conversion should instead be:
```latex
\leavevmode{\color{red} 

This is important content

}

This is normal content, \textcolor{orange}{warning content} and
\textcolor{red}{important content}.
```
Now pandoc, for some reason, won't give color `tex->PDF`, only `md->PDF` (which I've asked about [here](https://groups.google.com/forum/#!topic/pandoc-discuss/m5zNI4h9xoo)), but using using the syntax as above will make the .tex version compile correctly to PDF too.

**Comment by gandalfsaxe** [comment]
I've made a first attempt: https://github.com/gandalfsaxe/pandoc-latex-color/commit/b7d52d9d3dda5bf99eb95ce4a97dba63cddd99a5

1. divs now works correctly.

2. I've tried to get spans to work too, but RawInline automatically adds {} around the whole string, and I don't know how to customize that.

For input:
`[warning content]{latex-color=orange}`

I'm getting:
`{\textcolor{orange}{warning content}`
should have:
`\textcolor{orange}{warning content}`

( and really if I didn't cheat and hardcode an extra {, it would really be that I get:
`{\textcolor{orange}warning content}`

**Comment by chdemko** [comment]
I try to convert the latex code to pdf and it works perfectly.

~~~latex
\documentclass{article}

\usepackage{xcolor}

\begin{document}

{\color{red} 

This is important content

}

This is normal content, {\color{orange} warning content} and
{\color{red} important content}.

\end{document}
~~~

produces a correct pdf file (either by using pdflatex or latex then dvipdf)

**Comment by gandalfsaxe** [comment]
It only works because you're not involving pandoc. Try to convert the above using pandoc. Isn't writing input in non-latex (usually markdown) and then converting to latex/pdf the whole point of this, and all the other latex-related, pandoc filters? :)

You can see David Carlisle argue for using \textcolor for small paragraphs of color and `\color` for coloring larger spans of text [here](https://tex.stackexchange.com/a/86040/39354) on the question "What is the difference between \textcolor and \color?":
 
> Despite the name \textcolor also works in math mode. The main difference is just one of syntax, \textcolor takes text as an argument (like \textrm) \color affects all text to the end of the group (like \rmfamily). However \textcolor also executes \leavevmode which makes the color special occur in a much less destructive place as part of the paragraph rather than on a vertical list. So \textcolor is usually a better choice unless you are setting a colour for a large amount of text, such as the whole document.

Now to be perfectly honest, I don't know exactly what benefit `\textcolor` have over `\color` if you remember to enclose all colored sections with and I only vaguely understand what `\leavevmode` does in connection with this.

But I think I see what the problem was now. If you put the above into a .md file and convert to latex, pandoc will actually escape all the curly braces. i.e. this:

```latex
{\color{red} 

This is important content

}

This is normal content, {\color{orange} warning content} and
{\color{red} important content}.
```

becomes this:

```latex
\{\color{red}

This is important content

\}

This is normal content, \{\color{orange} warning content\} and
\{\color{red} important content\}.
```

So it turns out that pandoc will prepend any `{` and `}` braces at the beginning and end of words with a backslash, which of course in LaTeX escapes the curly braces so they don't do what they're supposed to. I don't know why pandoc does this, and I can find any mention of this auto-escaping of curly braces it in the manual.

## Solutions?

### Option 1: Use raw attribute
i.e. enclose all instances of colored text in:
```markdown
bla bla...
```{=latex}
{\color{red} 
This is important content
}
```
Bla bla...

The problem with this option is that it doesn't really allow for inline text colors.

### Option 2: Make the changes I suggested and add `\leavevmode` to divs and use `\textcolor` for spans.

Option 2 seems like the better choice. Unless you have a better idea or I overlooked something.

**Comment by chdemko** [comment]
I have 2 questions:

- Why do you use pandoc to compile LaTeX file?
- Do you use `-f latex` flag when reading from LaTeX in pandoc?

In the second case, pandoc does not take into account `\color` instructions:

~~~console
$ pandoc -f latex -t latex
{\color{red} 

This is important content

}

This is normal content, {\color{orange} warning content} and
{\color{red} important content}.
\color{red}
~~~

produces
~~~console
This is important content

This is normal content, { warning content} and { important content}.
~~~

**Comment by gandalfsaxe** [comment]
1. Not always, but sometimes, just because it can be convenient to do conversions in one step / using one tool. Since the results of `pandoc` and `pdflatex` is mostly identical, I like to find solutions that work for both (which they do for the most part).
2. I would expect `-f latex` to do nothing when working on a `.tex` file as input. As far as I can tell, that happens no matter what.

Overall I see no downside to making the two changes I suggested, only upsides, unless you can enlighten me :-) The current implementation only works going md->pdf, but not md->tex without modifications. The motivation is thta md->tex can be convenient sometimes if you want to use an advanced latex template and simply use pandoc to make the chapters to use in `input` or `include` commands in the master .tex file.

**Comment by chdemko** [comment]
1. I think that the `\leavevmode`directive could have some side effects on LaTeX code
2. your solution does not work: it lacks some `}` in your generated code and converting `This is normal content, \textcolor{orange}{warning content}` from latex to pdf does not generate color.

~~~console
$ pandoc -f latex -t latex
This is normal content, \textcolor{orange}{warning content}
~~~

generates

~~~console
This is normal content, {warning content}
~~~

**Comment by gandalfsaxe** [comment]
1. As I said in the first post, it seems like the \leavevmode when coloring whole paragraphs is recommended by several people (see [here ](https://tex.stackexchange.com/questions/207225/writing-paragraphs-in-textcolor)and [here](https://tex.stackexchange.com/questions/49910/how-to-colour-multiple-paragraphs and [here](https://tex.stackexchange.com/questions/86039/what-is-the-difference-between-textcolor-and-color/86040#86040))).
2. I know, and mentioned this in the [comment](https://github.com/chdemko/pandoc-latex-color/issues/1#issuecomment-401099706). I can't get it to make the right braces, don't know how to fix.
