### ISSUE TITLE
portable solution

### ISSUE THREAD

**Issue by jmb275** [chdemko/pandoc-latex-color#3]
I'm trying to use pandoc-latex-color. But I'd really like to have a portable solution that works via Dropbox on multiple computers. This is how I use latex templates across computers as well. It would be nice if there wasn't a machine-dependent "installation" process.

Is such a thing possible?

**Comment by chdemko** [comment]
there is not machine dependent process in the installation. pip is a standard way for installing python package

**Comment by jmb275** [comment]
Sorry. Let me explain again. If I use pip I need to install the python package on each computer (they're all Macs BTW). What I'd like to do is be able to put the pandoc-latex-color.py and any associated scripts in the ~/.pandoc/filters/ directory and have it work across multiple computers without needing to install using pip on each computer. 

Is that possible?

**Comment by chdemko** [comment]
You can use

~~~console
$ pip install --user pandoc-latex-color
~~~
and add the `$HOME/.local/bin` folder (on a MacOS, it could be different) to the `$PATH` variable.

**Comment by jmb275** [comment]
Thanks.
