### ISSUE TITLE
code blocks

### ISSUE THREAD

**Issue by jmb275** [chdemko/pandoc-latex-color#4]
I've been using pandoc-latex-color successfully. But I can't seem to get colored code blocks.

I have
\-\-\-
pandoc-latex-color:
  - classes: [soln]
    color: red
\-\-\-

in the header and then 

   \`\`\`{.soln}
	int main()
	{
		printf("hello\n");
		return 0;
	}
   \`\`\`

in my document. I've tried various combinations and can't get any coloring in a fenced code block. Is this not possible?

**Comment by chdemko** [comment]
No, it's currently not possible. It is only applied to div or span (not codeblock or code elements)
