### ISSUE TITLE
Error in Nested Blocks

### ISSUE THREAD

**Issue by damon-sava-stanley** [chdemko/pandoc-latex-color#5]
Inside divs with multiple nested blocks (whose final block is not a paragraph), this filter leads to malformed output. For example for the input

```markdown
::: {latex-color="red"}
Para

1. List
:::
```
leads to the malformed output

```latex
{\color{red} Para

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  List}
\end{enumerate}
```

The culprit is line 195-219 in `pandoc_latex_color.py` where the raw-inline is added before the first inline (so before the paragraph) but after the last inline (so after the last item in the list (but before the list closes).

**Comment by chdemko** [comment]
Thanks, could you propose a pull request?
